### PR TITLE
prevent unexpected crash at startup

### PR DESCRIPTION
**Pull request by pmp-p**
at least  on :
pygame 2.1.3.dev5 (SDL 2.0.14, Python 3.10.5)

### CODE REVIEW

**Comment by KennedyRichard** [comment]
Hello, Mr. Peny,

Thank you for your contribution.

Before I accept the changes, could you please share the log with the error message here?

The logs will be on the same spot where nodezator is installed, in a folder called **logs** I'd just like to know a bit more about the error/crash just to ensure the change on your pull request will prevent all possible ramifications of the problem. Thank you!

**Comment by pmp-p** [comment]
log in site-packages/nodezator
```
{'exc_info': None, 'func_name': '<module>', 'level': 'INFO', 'lineno': 217, 'message': 'Configured logging.', 'name': 'app.logman.main', 'timestamp': '2022-06-20 19:38:20.044276'},
{'exc_info': None, 'func_name': '<module>', 'level': 'DEBUG', 'lineno': 232, 'message': 'OS/system name is Linux', 'name': 'app.logman.main', 'timestamp': '2022-06-20 19:38:20.044498'},
{'exc_info': None, 'func_name': '<module>', 'level': 'DEBUG', 'lineno': 235, 'message': "Architecture info is ('64bit', 'ELF')", 'name': 'app.logman.main', 'timestamp': '2022-06-20 19:38:20.047824'},
{'exc_info': None, 'func_name': '<module>', 'level': 'DEBUG', 'lineno': 240, 'message': 'Python version is 3.10.5', 'name': 'app.logman.main', 'timestamp': '2022-06-20 19:38:20.048048'},
{'exc_info': None, 'func_name': '<module>', 'level': 'DEBUG', 'lineno': 243, 'message': 'Python implementation is CPython', 'name': 'app.logman.main', 'timestamp': '2022-06-20 19:38:20.048219'},
{'exc_info': None, 'func_name': '<module>', 'level': 'DEBUG', 'lineno': 248, 'message': 'Checking pygame module availability.', 'name': 'app.logman.main', 'timestamp': '2022-06-20 19:38:20.048425'},
{'exc_info': None, 'func_name': '<module>', 'level': 'DEBUG', 'lineno': 280, 'message': 'pygame version is 2.1.3', 'name': 'app.logman.main', 'timestamp': '2022-06-20 19:38:20.751625'},
{'exc_info': None, 'func_name': '<module>', 'level': 'DEBUG', 'lineno': 286, 'message': 'Nodezator version is 1.0.8 (release_candidate)', 'name': 'app.logman.main', 'timestamp': '2022-06-20 19:38:20.751827'},
{'exc_info': None, 'func_name': '<module>', 'level': 'DEBUG', 'lineno': 292, 'message': 'UTC offset (timezone) is +0200', 'name': 'app.logman.main', 'timestamp': '2022-06-20 19:38:20.751997'},
{'exc_info': None, 'func_name': 'main', 'level': 'INFO', 'lineno': 51, 'message': 'Loading application.', 'name': 'app.nodezator.__main__', 'timestamp': '2022-06-20 19:38:20.782330'},
```

python trace
```
user@pp ~ $ nodezator 
Fatal Python error: pygame_parachute: (pygame parachute) Segmentation Fault
Python runtime state: initialized

Current thread 0x00007f61fc155740 (most recent call first):
  File "/Users/user/.local/lib/python3.10/site-packages/nodezator/fontsman/preview/render.py", line 57 in <genexpr>
  File "/Users/user/.local/lib/python3.10/site-packages/nodezator/classes2d/collections.py", line 38 in __init__
  File "/Users/user/.local/lib/python3.10/site-packages/nodezator/fontsman/preview/render.py", line 54 in render_font_preview
  File "/Users/user/.local/lib/python3.10/site-packages/nodezator/fontsman/preview/cache.py", line 121 in __getitem__
  File "/Users/user/.local/lib/python3.10/site-packages/nodezator/widget/pathpreview/font.py", line 190 in blit_path_representation
  File "/Users/user/.local/lib/python3.10/site-packages/nodezator/widget/pathpreview/base.py", line 279 in update_image
  File "/Users/user/.local/lib/python3.10/site-packages/nodezator/widget/pathpreview/base.py", line 169 in __init__
  File "/Users/user/.local/lib/python3.10/site-packages/nodezator/graphman/widget/picker/subforms.py", line 680 in create_fontpreview_subform
  File "/Users/user/.local/lib/python3.10/site-packages/nodezator/graphman/widget/picker/main.py", line 282 in build_widget_subforms
  File "/Users/user/.local/lib/python3.10/site-packages/nodezator/graphman/widget/picker/main.py", line 175 in __init__
  File "/Users/user/.local/lib/python3.10/site-packages/nodezator/graphman/widget/picker/main.py", line 587 in <module>
  File "<frozen importlib._bootstrap>", line 241 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 883 in exec_module
  File "<frozen importlib._bootstrap>", line 688 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1006 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1027 in _find_and_load
  File "/Users/user/.local/lib/python3.10/site-packages/nodezator/editing/objinsert.py", line 34 in <module>
  File "<frozen importlib._bootstrap>", line 241 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 883 in exec_module
  File "<frozen importlib._bootstrap>", line 688 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1006 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1027 in _find_and_load
  File "/Users/user/.local/lib/python3.10/site-packages/nodezator/editing/main.py", line 12 in <module>
  File "<frozen importlib._bootstrap>", line 241 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 883 in exec_module
  File "<frozen importlib._bootstrap>", line 688 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1006 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1027 in _find_and_load
  File "/Users/user/.local/lib/python3.10/site-packages/nodezator/winman/main.py", line 57 in <module>
  File "<frozen importlib._bootstrap>", line 241 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 883 in exec_module
  File "<frozen importlib._bootstrap>", line 688 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1006 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1027 in _find_and_load
  File "/Users/user/.local/lib/python3.10/site-packages/nodezator/mainloop.py", line 52 in <module>
  File "<frozen importlib._bootstrap>", line 241 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 883 in exec_module
  File "<frozen importlib._bootstrap>", line 688 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1006 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1027 in _find_and_load
  File "/Users/user/.local/lib/python3.10/site-packages/nodezator/__main__.py", line 54 in main
  File "/Users/user/.local/bin/nodezator", line 8 in <module>

Extension modules: pygame.base, pygame.constants, pygame.rect, pygame.rwobject, pygame.surflock, pygame.bufferproxy, pygame.math, pygame.surface, pygame.display, pygame.draw, pygame.event, pygame.imageext, pygame.image, pygame.joystick, pygame.key, pygame.mouse, pygame.time, pygame.mask, pygame.pixelcopy, pygame.transform, pygame.font, pygame.mixer_music, pygame.mixer, pygame.scrap, numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, pygame.context, pygame._freetype (total: 39)
Aborted
```

**Comment by pmp-p** [comment]
Also, since we don't know yet if crash is in pygame or sdl2_ttf, it would be wise to check that every fontpath given to 
pygame.font.Font()  is a valid non zero file

on affected system a simple repro would be 
```
import pygame;pygame.init();  font = pygame.font.Font(".",10); font.render(" ",True,(0,0,0,),(255,255,255,))
```

**Comment by KennedyRichard** [comment]
Thank you. It seems the problem is not with Nodezator then. I'll be back in a couple of hous, make some extra needed commits and merge your pull request. Thank you again.

**Comment by KennedyRichard** [comment]
I'll merge your change to the main branch, but I'll make a quick alteration to make it so instead of returning a "draw not found" illustration (the circle with a line cutting it), the one similar to this emoji: :no_entry_sign:

**Comment by KennedyRichard** [comment]
All changes done.

**Pull request merged**
